server:
  port: 3300
spring:
  application:
    name: wxyy
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.105.140.239:3306/wxyy?allowMultiQueries=true
    username: root
    password: 123456a?
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /**
mybatis:
  mapper-locations: classpath*:mapper/web/*.xml,mapper/wx/*.xml
  configuration:
    call-setters-on-nulls: true
logging:
  file: wxyy.log
